### ISSUE TITLE
Recipe Issues

### ISSUE THREAD

**Issue by Mirv** [jatwell93/rubyproject#42]
- [ ] #35  -- Slight refactor in `before_action authenticate_user!`
- [ ] #36 -- Need to change views to show this one
- [ ] #39 -- Need to have one entry point for devise's current_user into each controller - separate module that interfaces devise current_user?
- [ ] Ingredients could probably use a has_many through ... which the join table would hold quantities
- [ ] Authorization to edit/delete/view things should be worked into one file, then pointed to by each controller (mixin module probably or pundit)

...pending more time...

**Comment by Mirv** [comment]
Moved this one to the projects area - @jatwell93

**Comment by Mirv** [comment]
@jatwell93  you know you can search closed issued right?  Also, in the project section under tracking - you can scroll the columns with the bar at the bottom
